### ISSUE TITLE
LinearTreeClassifier with Gini Index of 0 

### ISSUE THREAD

**Issue by sik-flow** [cerlymarco/linear-tree#16]
I am using the LinearTreeClassifier and ran into an issue where it throws an error due to the split having a Gini Index of 0 and only a single class in the node.  See below 
<img width="1057" alt="Screen Shot 2022-02-11 at 8 36 00 AM" src="https://user-images.githubusercontent.com/22510132/153611120-da21ab4d-397e-47ac-a07d-1c1c5fc11bab.png">

When looking at the splits with a decision tree we see the following: 

<img width="773" alt="Screen Shot 2022-02-11 at 8 36 10 AM" src="https://user-images.githubusercontent.com/22510132/153611246-c5c863d5-0aa2-4b38-8e0b-346bf797d0f1.png">

The colab notebook I used to create this issue is here: https://colab.research.google.com/drive/1NLWKZItwdRCmt6Dxmesqu75DLkXaJvs6?usp=sharing

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback. 

I think this happens because u are using a LinearTree**Regressor** for a classification problem. If u use a LinearTree**Classifier** (together with LogisticRegression) this shouldn't happen since in each partition split the class distributions are checked and the classifiers replaced by DummyEstimator in presence of a single class (as u can see [here](https://github.com/cerlymarco/linear-tree/blob/e07c2d485018ba0bb3defa81e3941b1b921faa49/lineartree/_classes.py#L117-L124))

All the best
